/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-08-28 07:15:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.teller.waitRoom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class waitRoom_002dteller_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/jsp/include/header_teller.jsp", Long.valueOf(1598598631305L));
    _jspx_dependants.put("jar:file:/D:/hanaProject-workspace/eclipse-workspace/wtpwebapps/spring-project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/footer.jsp", Long.valueOf(1598438778952L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598360198913L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>화상창구 상담 대기실 - 텔러</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicon/favicon.ico\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.dev.js\"></script>\r\n");
      out.write("<!-- <script src=\"/spring-project/js/teller/waitRoom/waitRoom-teller.js\"></script>  -->\r\n");
      out.write("<style>\r\n");
      out.write("\t.title{\r\n");
      out.write("\t\tfont-size: xxx-large;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top : 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv .col-md-7 {\r\n");
      out.write("\t\tflex: none;\r\n");
      out.write("\t\tmax-width : none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu {\r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top : 130px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#info {\r\n");
      out.write("\t\tfloat:left; \r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\twidth:50%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 20%;\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#clientCount {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 5%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#start {\r\n");
      out.write("\t\tfloat:left; \r\n");
      out.write("\t\tfont-size: x-large;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\twidth:50%;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tmargin-top: 10%;\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.job {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twidth: 250px;\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t\tborder-color: white;\r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\tborder-width: inherit;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tborder-radius: 20px 20px 20px 20px\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#modal {\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tz-index:1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal h2 {\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal button {\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\twidth:100px;\r\n");
      out.write("\t\tmargin-left:calc(100% - 100px - 10px);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal .modal_content {\r\n");
      out.write("\t\tposition : relative;\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\tpadding:20px 10px;\r\n");
      out.write("\t\tbackground:#fff;\r\n");
      out.write("\t\tborder:2px solid #ffffff;\r\n");
      out.write("\t\tleft:50%;\r\n");
      out.write("\t\ttop:40%;\r\n");
      out.write("\t\tfont-size:x-large;\r\n");
      out.write("\t\ttransform:translate(-50%, -50%);\r\n");
      out.write("\t\tborder-radius: 10px 10px 10px 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal .modal_layer {\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t\ttop:0;\r\n");
      out.write("\t\tleft:0;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tbackground:rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\tz-index:-1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\taside #link{\r\n");
      out.write("\t\tpadding-left: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\taside .refMsg {\r\n");
      out.write("\t\tmargin-top : 100px;\r\n");
      out.write("\t\tmargin-right : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btn-primary {\r\n");
      out.write("\t\twidth : 120px;\r\n");
      out.write("\t\theight : 120px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.stmInfo {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size: x-large;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#STMlink {\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\twidth : 350px;\r\n");
      out.write("\t\theight : 50px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#modal_close_btn {\r\n");
      out.write("\t\tborder-color: white;\r\n");
      out.write("\t\tborder-width: inherit;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tborder-radius: 10px 10px 10px 10px;\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bg-light {\r\n");
      out.write("\t\tbackground-color: #FFFFFF!important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.navbar.navbar-expand-lg.navbar-light.bg-light div.container {\r\n");
      out.write("\t\tpadding-left : 100;\r\n");
      out.write("\t\tmargin-left : 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.navbar.navbar-expand-lg.navbar-light.bg-light {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tborder-bottom-color: black;\r\n");
      out.write("\t\tborder-bottom-width: thin;\r\n");
      out.write("\t\tborder-bottom-style: solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-family: \"Hana B\";\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t<div class=\"container\" style=\"padding-left : 70px\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/teller\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/hanalogo.png\" style=\"width:150px; height:40px;\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"modal\">\r\n");
      out.write("\t\t\t<div class=\"modal_content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div align=\"center\" id=\"loading_image\" style=\"width:100%; height:100%; text-align:center; font-size: large; color:black; font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/loading.gif\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t손님, 잠시만 기다려주세요.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t텔러와 연결중입니다.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"modal_close_btn\">취소하기</button>\r\n");
      out.write("    \t\t\t<!-- \r\n");
      out.write("    \t\t\t<h2>모달 창</h2>\r\n");
      out.write("    \t\t\t<p>모달 창 입니다.</p>\r\n");
      out.write("    \t\t\t -->\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t<div class=\"modal_layer\"></div>    \t\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div id=\"page-content\">\r\n");
      out.write("    \t\t<div class=\"container text-center\">\r\n");
      out.write("    \t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t    \t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t    \t\t\t\t<div class=\"title\">웃는 얼굴로 손님을 맞아주세요. <svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-emoji-smile\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("  \t\t\t\t\t\t\t<path fill-rule=\"evenodd\" d=\"M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z\"/>\r\n");
      out.write("  \t\t\t\t\t\t\t<path fill-rule=\"evenodd\" d=\"M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683z\"/>\r\n");
      out.write("  \t\t\t\t\t\t\t<path d=\"M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</svg>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"info\">\r\n");
      out.write("\t\t\t\t\t\t\t오늘 맞이한 손님 1명<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"clientCount\">상담 대기 손님 0명</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"start\">\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/startCall.png\" style=\"width:7em; height:7em;\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"startCounseling\" value=\"업무 시작하기\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- \r\n");
      out.write("    \t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("    \t\t\t\t\t\t<div>\r\n");
      out.write("    \t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/startCall.png\" style=\"width:5em; height:5em;\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"startCounseling\" value=\"업무 시작하기\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#sticky-footer {\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tposition : fixed;\r\n");
      out.write("\t\tbottom : 0;\r\n");
      out.write("\t\tpadding : 30px;\r\n");
      out.write("\t\tz-index : 10;\r\n");
      out.write("\t\tflex-shrink: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<footer id=\"sticky-footer\" class=\"py-4 bg-dark text-white-50\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <small>Copyright &copy; Hana TI</small>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar host = 'https://192.168.217.52';\r\n");
      out.write("\t\tvar port = '1337';\r\n");
      out.write("\t\t//var url = 'https://192.168.217.52:1337'\r\n");
      out.write("\t\tvar url = 'https://localhost:1337'\r\n");
      out.write("\t\tvar socket;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconnectToServer();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction connectToServer() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\t'forceNew' : true\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t//var url = \"http://\" + host + \":\" + port;\r\n");
      out.write("\t\t\t//var url = \"https://\" + host + \":\" + port;\r\n");
      out.write("\t\t\tprintln(url);\r\n");
      out.write("\t\t\tsocket = io.connect(url, options);\r\n");
      out.write("\r\n");
      out.write("\t\t\tsocket.on('connect', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tprintln(\"웹 소켓 서버에 연결되었습니다. : \" + url);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsocket.on('check', function(event) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tconsole.log('check Event');\r\n");
      out.write("\t\t\t\t\tsocket.emit('type', 'waitTeller')\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//socket.emit('type', 'teller') 정의\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('ready', function(room) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar clientID = room.split(':')[0];\r\n");
      out.write("\t\t\t\t\tvar jobType = room.split(':')[1];\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tconsole.log(room)\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar keys = new Array();\r\n");
      out.write("\t\t\t\t\tkeys.push('userID');\r\n");
      out.write("\t\t\t\t\tkeys.push('jobType');\r\n");
      out.write("\t\t\t\t\tvar values = new Array();\r\n");
      out.write("\t\t\t\t\tvalues.push(clientID);\r\n");
      out.write("\t\t\t\t\tvalues.push(jobType);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//post_to_url(\"https://localhost:8811/spring-project/teller/bankCounter\", \"userID\", clientID);\r\n");
      out.write("\t\t\t\t\tpost_to_url(\"https://localhost:8811/spring-project/teller/bankCounter\", keys, values);\r\n");
      out.write("\t\t\t\t\t//location.href=\"https://localhost:8811/spring-project/teller/bankCounter\";\r\n");
      out.write("\t\t\t\t\tconsole.log('joined: ' + room);\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t// 'message' event 날아왔을 때 행동 정의\r\n");
      out.write("\t\t\t\tsocket.on('message', function(message) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(message ==='got user media') {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('waitClient', function(event) {\r\n");
      out.write("\t\t\t\t\tconsole.log('wait Client : ' + event);\r\n");
      out.write("\t\t\t\t\t$(\"#clientCount\").empty();\r\n");
      out.write("\t\t\t\t\t$(\"#clientCount\").append('상담 대기중인 손님 ' + event + '명');\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsocket.on('disconnect', function() {\r\n");
      out.write("\t\t\t\tprintln('웹 소켓 연결이 종료되었습니다.');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#startCounseling\").bind('click', function(event) {\r\n");
      out.write("\t\t\t//println('bankJob 버튼이 클릭되었습니다.');\r\n");
      out.write("\t\t\t//connectToServer('bankJob');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsendStart();\r\n");
      out.write("\t\t\t$(\"#modal\").fadeIn();\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"modal_close_btn\").onclick = function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#modal\").fadeOut();\r\n");
      out.write("\t\t\t//document.getElementById(\"modal\").style.display=\"none\";\r\n");
      out.write("\t\t\tsocket.emit('clientDisconnect');\r\n");
      out.write("    \t}   \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction sendStart() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(socket == undefined) {\r\n");
      out.write("\t\t\t\talert('You are not connected status. Connect Server.');\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsocket.emit('type', 'teller');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction println(data) {\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t$('#result').append('<p>' + data + '</p>')\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tfunction post_to_url(path, key, param) {\r\n");
      out.write("\t\tlet method = \"post\"; // 전송 방식 기본값을 POST로\r\n");
      out.write("  \t \t\r\n");
      out.write("  \t    var form = document.createElement(\"form\");\r\n");
      out.write("  \t    form.setAttribute(\"method\", method);\r\n");
      out.write("  \t    form.setAttribute(\"action\", path);\r\n");
      out.write("  \t    \r\n");
      out.write("  \t    for(let i = 0; i < key.length; i++) {\r\n");
      out.write("  \t    \tvar hiddenField = document.createElement(\"input\");\r\n");
      out.write("  \t    \thiddenField.setAttribute(\"type\", \"hidden\");\r\n");
      out.write("  \t    \thiddenField.setAttribute(\"name\", key[i]);\r\n");
      out.write("  \t    \thiddenField.setAttribute(\"value\", param[i]);\r\n");
      out.write("  \t    \tconsole.log(key[i]);\r\n");
      out.write("  \t    \tconsole.log(param[i]);\r\n");
      out.write("  \t    \t\r\n");
      out.write("  \t    \tform.appendChild(hiddenField);\r\n");
      out.write("  \t    }\r\n");
      out.write("  \t    \r\n");
      out.write("  \t    document.body.appendChild(form);\r\n");
      out.write("  \t    form.submit();\r\n");
      out.write("  \t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/include/header_teller.jsp(47,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty tellerVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
          out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" style=\"float: right; font-size: large;\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ tellerVO.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right animate slideIn\" aria-labelledby=\"navbarDropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/teller/logout\">로그아웃</a>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/teller/login\" style=\"padding-right: 30px; font-size: x-large;\">로그인</a>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
