/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-08-28 06:10:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.client.waitRoom;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class waitRoom_002dclient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/hanaProject-workspace/eclipse-workspace/wtpwebapps/spring-project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/include/footer.jsp", Long.valueOf(1598438778952L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598360198913L));
    _jspx_dependants.put("/WEB-INF/jsp/include/header.jsp", Long.valueOf(1598442581843L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하나은행 화상창구 대기실</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/favicon/favicon.ico\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.dev.js\"></script>\r\n");
      out.write("<!-- <script src=\"/spring-project/js/client/waitRoom/waitRoom-client.js\"></script>  -->\r\n");
      out.write("<style>\r\n");
      out.write("\t.title{\r\n");
      out.write("\t\tfont-size: xxx-large;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top : 120px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdiv .col-md-7 {\r\n");
      out.write("\t\tflex: none;\r\n");
      out.write("\t\tmax-width : none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.menu {\r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tmargin-top : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.job {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twidth: 250px;\r\n");
      out.write("\t\theight : 100px;\r\n");
      out.write("\t\tborder-color: white;\r\n");
      out.write("\t\tfont-size: xx-large;\r\n");
      out.write("\t\tborder-width: inherit;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tborder-radius: 20px 20px 20px 20px\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#modal {\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tz-index:1;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal h2 {\r\n");
      out.write("\t\tmargin:0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal button {\r\n");
      out.write("\t\tdisplay:inline-block;\r\n");
      out.write("\t\twidth:100px;\r\n");
      out.write("\t\tmargin-left:calc(100% - 100px - 10px);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal .modal_content {\r\n");
      out.write("\t\tposition : relative;\r\n");
      out.write("\t\twidth:500px;\r\n");
      out.write("\t\tpadding:20px 10px;\r\n");
      out.write("\t\tbackground:#fff;\r\n");
      out.write("\t\tborder:2px solid #ffffff;\r\n");
      out.write("\t\tleft:50%;\r\n");
      out.write("\t\ttop:40%;\r\n");
      out.write("\t\tfont-size:x-large;\r\n");
      out.write("\t\ttransform:translate(-50%, -50%);\r\n");
      out.write("\t\tborder-radius: 10px 10px 10px 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#modal .modal_layer {\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t\ttop:0;\r\n");
      out.write("\t\tleft:0;\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tbackground:rgba(0, 0, 0, 0.5);\r\n");
      out.write("\t\tz-index:-1;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\taside #link{\r\n");
      out.write("\t\tpadding-left: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\taside .refMsg {\r\n");
      out.write("\t\tmargin-top : 80px;\r\n");
      out.write("\t\tmargin-right : 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btn-primary {\r\n");
      out.write("\t\twidth : 120px;\r\n");
      out.write("\t\theight : 120px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.stmInfo {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfont-size: x-large;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#STMlink {\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t\twidth : 350px;\r\n");
      out.write("\t\theight : 50px;\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#modal_close_btn {\r\n");
      out.write("\t\tborder-color: white;\r\n");
      out.write("\t\tborder-width: inherit;\r\n");
      out.write("\t\tbackground-color: lightgray;\r\n");
      out.write("\t\tborder-radius: 10px 10px 10px 10px;\r\n");
      out.write("\t\tfont-size: large;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#clientCount{\r\n");
      out.write("\t\tfont-size : x-large;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/simple-sidebar.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\thtml, body {\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.bg-light {\r\n");
      out.write("\t\tbackground-color: #FFFFFF!important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.navbar.navbar-expand-lg.navbar-light.bg-light div.container {\r\n");
      out.write("\t\tpadding-left : 100;\r\n");
      out.write("\t\tmargin-left : 100;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav.navbar.navbar-expand-lg.navbar-light.bg-light {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tborder-bottom-color: black;\r\n");
      out.write("\t\tborder-bottom-width: thin;\r\n");
      out.write("\t\tborder-bottom-style: solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-family: \"Hana B\";\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Bootstrap core JavaScript -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t<div class=\"container\" style=\"padding-left : 70px\">\r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/hanalogo.png\" style=\"width:150px; height:40px;\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"modal\">\r\n");
      out.write("\t\t\t<div class=\"modal_content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div align=\"center\" id=\"loading_image\" style=\"width:100%; height:100%; text-align:center; font-size: large; color:black; font-weight:bold;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/loading.gif\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"clientCount\">상담 대기중인 손님 0명</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t손님, 잠시만 기다려주세요.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t텔러와 연결중입니다.\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"modal_close_btn\">취소하기</button>\r\n");
      out.write("    \t\t\t<!-- \r\n");
      out.write("    \t\t\t<h2>모달 창</h2>\r\n");
      out.write("    \t\t\t<p>모달 창 입니다.</p>\r\n");
      out.write("    \t\t\t -->\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t<div class=\"modal_layer\"></div>    \t\r\n");
      out.write("    </div>\r\n");
      out.write("\t<aside style=\"float: right; align-content: center;\">\r\n");
      out.write("\t\t<div class=\"refMsg\" style=\"font-size: large\">상담 전 참고해보세요!</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"link\"><br>\r\n");
      out.write("\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/list.jpg\" style=\"width:120px;\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"deposit\" style=\"font-size:x-large; background-color: #008C8C; border-color: #008C8C; border-radius: 20px 20px 20px 20px;\">예/적금</button><br><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"card\" style=\"font-size:x-large; background-color: #008C8C; border-color: #008C8C; border-radius: 20px 20px 20px 20px;\">카드</button><br><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"fund\" style=\"font-size:x-large; background-color: #008C8C; border-color: #008C8C; border-radius: 20px 20px 20px 20px;\">펀드</button><br><br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\" id=\"insurance\" style=\"font-size:x-large; background-color: #008C8C; border-color: #008C8C; border-radius: 20px 20px 20px 20px;\">보험</button><br><br>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</aside>    \t\t\t\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div id=\"page-content\">\r\n");
      out.write("    \t\t<div class=\"container text-center\">\r\n");
      out.write("    \t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t    \t\t\t<div class=\"col-md-7\">\r\n");
      out.write("    \t\t\t\t\t<div class=\"title\">손님, 원하시는 업무를 선택해주세요.</div>\r\n");
      out.write("    \t\t\t\t\t<div class=\"menu\">\r\n");
      out.write("    \t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"bankJob\" value=\"예/적금 업무\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"cardJob\" value=\"카드 업무\">\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"efJob\" value=\"전자금융 업무\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"job\" id=\"certificationJob\" value=\"증명서 발급 업무\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("\t    \t\t\t<div class=\"stmInfo\">\r\n");
      out.write("\t    \t\t\t\t<br><br><br>\r\n");
      out.write("\t    \t\t\t\t각종 발급 업무는 STM창구를 이용하시면 더 빨리 해결하실 수 있습니다.<br>\r\n");
      out.write("\t    \t\t\t\t<input type=\"button\" id=\"STMlink\" value=\"STM 위치 조회\">\r\n");
      out.write("\t    \t\t\t</div>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#sticky-footer {\r\n");
      out.write("\t\twidth : 100%;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tposition : fixed;\r\n");
      out.write("\t\tbottom : 0;\r\n");
      out.write("\t\tpadding : 30px;\r\n");
      out.write("\t\tz-index : 10;\r\n");
      out.write("\t\tflex-shrink: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<footer id=\"sticky-footer\" class=\"py-4 bg-dark text-white-50\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("      <small>Copyright &copy; Hana TI</small>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("/**\r\n");
      out.write(" * \r\n");
      out.write(" */\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t\tvar host = 'https://192.168.217.52';\r\n");
      out.write("\t\tvar port = '1337';\r\n");
      out.write("\t\t//var url = 'https://192.168.217.52:1337'\r\n");
      out.write("\t\tvar url = 'https://localhost:1337'\r\n");
      out.write("\t\tvar socket;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar bool = true;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jobType;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//$(\"#loading_image\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction connectToServer() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar options = {\r\n");
      out.write("\t\t\t\t'forceNew' : true\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t//var url = \"http://\" + host + \":\" + port;\r\n");
      out.write("\t\t\t//var url = \"https://\" + host + \":\" + port;\r\n");
      out.write("\t\t\tprintln(url);\r\n");
      out.write("\t\t\tsocket = io.connect(url, options);\r\n");
      out.write("\r\n");
      out.write("\t\t\tsocket.on('connect', function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tprintln(\"웹 소켓 서버에 연결되었습니다. : \" + url);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('check', function(event) {\r\n");
      out.write("\t\t\t\t\tconsole.log(event);\r\n");
      out.write("\t\t\t\t\tprintln('check Event');\r\n");
      out.write("\t\t\t\t\t//socket.emit('type', 'client:' + 'jinwoo11')\r\n");
      out.write("\t\t\t\t\tsocket.emit('type', 'client:' + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' + ':' + jobType)\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('ready', function(id) {\r\n");
      out.write("\t\t\t\t\tprintln('ready Event');\r\n");
      out.write("\t\t\t\t\t//location.href=\"https://localhost:8811/spring-project/bankCounter-client.jsp\";\r\n");
      out.write("\t\t\t\t\tlocation.href=\"https://localhost:8811/spring-project/bankCounter\";\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('waitClient', function(event) {\r\n");
      out.write("\t\t\t\t\tconsole.log('wait Client : ' + event);\r\n");
      out.write("\t\t\t\t\t$(\"#clientCount\").empty();\r\n");
      out.write("\t\t\t\t\t$(\"#clientCount\").append('상담 대기중인 손님 ' + event + '명');\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tsocket.on('message', function(message) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(message ==='got user media') {\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsocket.on('disconnect', function() {\r\n");
      out.write("\t\t\t\tprintln('웹 소켓 연결이 종료되었습니다.');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".job\").bind('click', function(event) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tjobType = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconnectToServer();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//$(\"#loading_image\").show();\r\n");
      out.write("\t\t\t//document.getElementById(\"modal\").style.display=\"block\";\r\n");
      out.write("\t\t\t$(\"#modal\").fadeIn();\r\n");
      out.write("\t\t\t/*\r\n");
      out.write("\t\t\tif(bool) {\r\n");
      out.write("\t\t\t\tprintln('bankJob 버튼이 클릭되었습니다.');\r\n");
      out.write("\t\t\t\tconnectToServer('bankJob');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//$(\"#loading_image\").show();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"modal\").style.display=\"block\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t//$(\"#loading_image\").hide();\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"modal\").style.display=\"none\";\r\n");
      out.write("\t\t\t\tsocket.emit('clientDisconnect');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tbool = !bool\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".btn-primary\").bind('click', function(event) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar openNewWindow = window.open(\"about:blank\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif($(this).attr('id') == 'deposit'){\r\n");
      out.write("\t\t\t\topenNewWindow.location.href = \"https://www.kebhana.com/cont/mall/mall08/mall0805/index.jsp?catId=spb_2811\";\r\n");
      out.write("\t\t\t} else if($(this).attr('id') == 'card') {\r\n");
      out.write("\t\t\t\topenNewWindow.location.href = \"https://www.hanacard.co.kr/index2.jsp\";\r\n");
      out.write("\t\t\t} else if($(this).attr('id') == 'fund') {\r\n");
      out.write("\t\t\t\topenNewWindow.location.href = \"https://www.kebhana.com/cont/mall/mall26/mall2602/index.jsp?_menuNo=62634\";\r\n");
      out.write("\t\t\t} else if($(this).attr('id') == 'insurance') {\r\n");
      out.write("\t\t\t\topenNewWindow.location.href = \"https://www.kebhana.com/cont/mall/mall08/mall0805/index.jsp?insSch=insAllSch&_menuNo=99073\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#STMlink\").bind('click', function(event) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar openNewWindow = window.open(\"about:blank\");\r\n");
      out.write("\t\t\topenNewWindow.location.href = \"https://www.kebhana.com/cont/info/info03/info030d/index.jsp\";\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tdocument.getElementById(\"modal_close_btn\").onclick = function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#modal\").fadeOut();\r\n");
      out.write("\t\t\t//document.getElementById(\"modal\").style.display=\"none\";\r\n");
      out.write("\t\t\tsocket.emit('clientDisconnect');\r\n");
      out.write("    \t}   \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction println(data) {\r\n");
      out.write("\t\t\tconsole.log (data);\r\n");
      out.write("\t\t\t$('#result').append('<p>' + data + '</p>')\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/include/header.jsp(47,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty userVO }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
          out.write("\t\t\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\" style=\"float: right; font-size: large;\">\r\n");
          out.write("\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ userVO.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("\t\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"dropdown-menu dropdown-menu-right animate slideIn\" aria-labelledby=\"navbarDropdown\">\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a>\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Another action</a>\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\">로그아웃</a>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\" style=\"padding-right: 30px; font-size: x-large;\">로그인</a>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
